language: r
sudo: false

install:
  - Rscript -e 'install.packages(c("devtools","roxygen2","testthat"));devtools::install_deps("RPackage")'
script:
  - Rscript -e 'devtools::check("RPackage")'

cache:
  directories:
    - $TRAVIS_BUILD_DIR/packrat/src
    - $TRAVIS_BUILD_DIR/packrat/lib
  packages: true

r_packages:
  - ggplot2
  - Rcmdr
  - datasets
  - nortest
  - knitr

notifications:
  email:
    on_success: change
    on_failure: change
